### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by ZerLock** [ZiplEix/logger#7]
**Describe the bug**
Currently, the README is not clear and specify this logger is only available for C

**To Reproduce**
Just see the repository :joy: 

**Expected behavior**
/

**Screenshots**
![image](https://user-images.githubusercontent.com/47077683/192163019-f2613010-3d7f-460c-b116-1f7f2ebaad86.png)
![image](https://user-images.githubusercontent.com/47077683/192163026-b1a380d5-cf80-4323-b85a-c5b60f723f78.png)

**OS (indicate te OS you use when the bug appeard):**
/

**Additional context**
/

**Comment by ZiplEix** [comment]
Done
